# Generated by Django 4.2 on 2025-05-31 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
        ('department_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.customuser'),
        ),
        migrations.AddField(
            model_name='semesters',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department_management.course'),
        ),
        migrations.AddField(
            model_name='departments',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.customuser'),
        ),
        migrations.AddField(
            model_name='course',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department_management.departments'),
        ),
    ]
